--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/PMHopper
build-by-default: true
branches:
- master
projects:
  PMHopper:
    path: ""
    libs:
      - src: muqsit/asynciterator/AsyncIterator
        version: ^1.1.2
...
