# PMHopper v0.0.1 Config file

# Time (in ticks) until the next transfer
# This transfer cooldown applies only to container -> container transfers. It does not cover item entity -> hopper
# transfers.
# Default: 8
transfer-cooldown: 8

# Number of items sucked at once from or by a container
# Default: 1
items-sucked: 1

# Interval (in ticks) between checking for dropped items
# Default: 1
items-sucking-tick-rate: 1

# Whether to enable the /pmhopper debug command (requires permission: "pmhopper.command")
# Default: false
debug: false