# PMHopper v1.0.0 Config file

# Item transfer Behaviour
# Every "tick-rate" game ticks, "per-tick" items are transferred from container to container.
# Default:
#   tick-rate: 8
#   per-tick: 1
transfer:
  tick-rate: 8
  per-tick: 1

# Item-sucking Behaviour
# Every "tick-rate" game ticks, "per-tick" number of item entities scan for hoppers below them.
# Default:
#  tick-rate: 1
#  per-tick: 16
item-sucking:
  tick-rate: 1
  per-tick: 16

# Whether to enable the /pmhopper debug command (requires permission: "pmhopper.command")
# Default: false
debug: false