# PMHopper v1.0.0 Config file

# Item transfer Behaviour
# Every "tick-rate" game ticks, "per-tick" items are transferred from container to container.
# Default:
#   tick-rate: 8
#   per-tick: 1
transfer:
  tick-rate: 8
  per-tick: 1

# Item-sucking Behaviour
# Every "tick-rate" game ticks, "per-tick" number of item entities scan for hoppers below them.
# Default:
#   tick-rate: 1
#   per-tick: 16
item-sucking:
  tick-rate: 1
  per-tick: 16

# Hopper <-> Container Transfer Scheduler
# Specify the scheduler to use for transfers between hoppers and containers.
# Available scheduler types: default, load_balancing
# If load_balancing is used, load_balancing.capacity number of hoppers will be ticked each tick.
# Default:
#   type: default
#   load_balancing:
#     capacity: 100
scheduler:
  type: default
  load_balancing:
    capacity: 100

# Whether to enable the /pmhopper debug command (requires permission: "pmhopper.command")
# Default: false
debug: false